CreateIntelBSPPackage.py: update to the new release fields
We weren't picking up the new release fields. This keeps us
from having an undefined reference to is_milestone.

Signed-off-by: Beth Flanagan <elizabeth.flanagan@intel.com>