CreateAutoConf.py: check for empty env history variables before using
I saw this error on a new AB setup:

File "/home/pokybuild/yocto-autobuilder/lib/python2.7/site-packages/autobuilder/buildsteps/CreateAutoConf.py", line 181, in start
    ta_history_repos=ast.literal_eval(os.environ.get('BUILD_HISTORY_THROWAWAY_WHITELIST').encode('utf-8'))
    exceptions.AttributeError: 'NoneType' object has no attribute 'encode'

Since the code above line 181 checks for either BUILD_HISTORY_THROWAWAY_WHITELIST
or BUILD_HISTORY_WHITELIST being set, it's possible one of them could be empty.

Signed-off-by: Bill Randle <william.c.randle@intel.com>