BuildImages: ensure self.command != None even when skipping step
RunProcess._startCommand throws an Exception when a ShellCommand's
command property is None, even if the buildstep is being skipped:

error in RunProcess._startCommand
Traceback (most recent call last):
  File "/home/pokybuild/yocto-autobuilder/lib/python2.7/site-packages/buildbot_slave-0.8.8-py2.7.egg/buildslave/runprocess.py", line 386, in start
    self._startCommand()
  File "/home/pokybuild/yocto-autobuilder/lib/python2.7/site-packages/buildbot_slave-0.8.8-py2.7.egg/buildslave/runprocess.py", line 438, in _startCommand
    display = shell_quote(self.fake_command)
  File "/home/pokybuild/yocto-autobuilder/lib/python2.7/site-packages/buildbot_slave-0.8.8-py2.7.egg/buildslave/runprocess.py", line 61, in shell_quote
    return " ".join([ quote(e) for e in cmd_list ])
TypeError: 'NoneType' object is not iterable

Signed-off-by: Joshua Lock <joshua.g.lock@intel.com>