Revert "RunSanityTests: reset auto.conf when tests are done"
This results in Exceptions being thrown due to auto.conf missing
on several of the buildsets in buildset-config.controller:

Traceback (most recent call last):
  File "/home/pokybuild/yocto-autobuilder/lib/python2.7/site-packages/Twisted-12.2.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 290, in addCallbacks
    self._runCallbacks()
  File "/home/pokybuild/yocto-autobuilder/lib/python2.7/site-packages/Twisted-12.2.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 551, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/pokybuild/yocto-autobuilder/lib/python2.7/site-packages/Twisted-12.2.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 368, in callback
    self._startRunCallbacks(result)
  File "/home/pokybuild/yocto-autobuilder/lib/python2.7/site-packages/Twisted-12.2.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 464, in _startRunCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/home/pokybuild/yocto-autobuilder/lib/python2.7/site-packages/Twisted-12.2.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 551, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/pokybuild/yocto-autobuilder/lib/python2.7/site-packages/buildbot-0.8.8-py2.7.egg/buildbot/process/buildstep.py", line 866, in <lambda>
    d.addCallback(lambda res: self.commandComplete(cmd))
  File "/home/pokybuild/yocto-autobuilder/lib/python2.7/site-packages/autobuilder/buildsteps/RunSanityTests.py", line 84, in commandComplete
    os.remove(autoconf)
exceptions.OSError: [Errno 2] No such file or directory: '/home/pokybuild/yocto-autobuilder/yocto-worker/nightly-arm64/build/build/conf/auto.conf'

This reverts commit e675e6a7e8d06dcd0141394f329b74c2f5da21fa.