autobuilder/Autobuilder.p: Add missing import of buildbot.util.
When try to start Autobuilder fails with the next exception,

2016-06-07 17:06:45-0500 [-] LOADING CONFIG FILE
2016-06-07 17:06:45-0500 [-] error while parsing config file:

Traceback (most recent call last):
          File
"/home/alimon/repos/yocto-autobuilder/lib/python2.7/site-packages/Twisted-12.2.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py",
line 551, in _runCallbacks
......
......
......
          File
"/home/alimon/repos/yocto-autobuilder/lib/python2.7/site-packages/autobuilder/Autobuilder.py",
line 54, in createBuildsets
            util.naturalSort(buildersSorted)
        exceptions.NameError: global name 'util' is not defined

Signed-off-by: Aníbal Limón <anibal.limon@linux.intel.com>